#!/bin/bash


SUCCESS=" 0% packet loss"
if [ -z $1 -o -z $2 ]
then
	echo "usage ping_ip <count> <timeout>"
	exit 0
fi
for i in {1..255}
do 
	result=`ping "192.168.1.${i}" -c 1 -w 2`
	if [[ ${result} == *${SUCCESS}* ]] 
	then
	echo "192.168.1.${i} is exist"
	fi
done
